'use strict';
/**
 * FurcaRiskAI – GitHub Actions Step Summary Generator
 *
 * Reads tests/results.json and writes the structured summary to:
 *   1. $GITHUB_STEP_SUMMARY (when running in GitHub Actions)
 *   2. "Test Results/Summary/summary.md" (always)
 *
 * Usage:
 *   node reporters/generate-summary.js
 *
 * Environment variables:
 *   GITHUB_PAGES_URL       – Live deployment URL  (e.g. https://user.github.io/repo/)
 *   GITHUB_STEP_SUMMARY    – Set automatically by GitHub Actions
 */

const fs   = require('fs');
const path = require('path');

const resultsFile = path.resolve(__dirname, '../results.json');
const summaryDir  = path.resolve(__dirname, '../../Test Results/Summary');

if (!fs.existsSync(resultsFile)) {
    console.error('ERROR: results.json not found at ' + resultsFile);
    process.exit(1);
}

const r            = JSON.parse(fs.readFileSync(resultsFile, 'utf8'));
const pagesUrl     = (process.env.GITHUB_PAGES_URL || 'https://<github-username>.github.io/<repository-name>/').replace(/\/$/, '') + '/';
const durationSec  = r.durationMs ? (r.durationMs / 1000).toFixed(2) : '--';
const dateStr      = new Date(r.executionDate || Date.now()).toUTCString();
const passRate     = r.passRate || '0%';
const passed       = r.passed  || 0;
const failed       = r.failed  || 0;
const skipped      = r.skipped || 0;
const total        = r.totalTests || 0;

// ── Failed tests section ─────────────────────────────────────────────────────
const failedTests = (r.tests || []).filter(t => t.status !== 'PASS');
const failedLines = failedTests.length > 0
    ? failedTests.map(t => `- **${t.name}**: \`${t.error || 'Unknown failure'}\``).join('\n')
    : '_None – all tests passed_ ✅';

// ── Markdown content ─────────────────────────────────────────────────────────
const md = [
    '# 🌐 Live GitHub Pages E2E Test Summary',
    '',
    `> **Deployment URL:** [${pagesUrl}](${pagesUrl})`,
    '',
    '---',
    '',
    '## 📊 Test Results',
    '',
    `| Metric       | Value        |`,
    `|:-------------|:-------------|`,
    `| Total Tests  | **${total}**     |`,
    `| ✅ Passed    | **${passed}**    |`,
    `| ❌ Failed    | **${failed}**    |`,
    `| ⏭ Skipped   | **${skipped}**   |`,
    `| Pass Rate    | **${passRate}**  |`,
    `| Duration     | ${durationSec}s  |`,
    `| Build        | #${r.buildNumber || 'local'} |`,
    `| Executed At  | ${dateStr}       |`,
    `| Platform     | ${r.platform || 'Web'}      |`,
    '',
    '---',
    '',
    '## ❌ Failed Tests',
    '',
    failedLines,
    '',
    '---',
    '',
    '## 🔗 Reports',
    '',
    `- [📄 HTML Execution Report](${pagesUrl}reports/latest/execution-report.html)`,
    `- [📁 Test Artifacts](${pagesUrl}reports/latest/)`,
    '',
    '---',
    '',
    `*Generated by FurcaRiskAI CI/CD on ${dateStr}*`
].join('\n');

// ── Write to summary dir ─────────────────────────────────────────────────────
if (!fs.existsSync(summaryDir)) fs.mkdirSync(summaryDir, { recursive: true });
const summaryPath = path.join(summaryDir, 'summary.md');
fs.writeFileSync(summaryPath, md, 'utf8');
console.log('Summary written: ' + summaryPath);

// ── Append to GitHub Actions Step Summary ───────────────────────────────────
const gaSummaryFile = process.env.GITHUB_STEP_SUMMARY;
if (gaSummaryFile) {
    fs.appendFileSync(gaSummaryFile, '\n' + md + '\n', 'utf8');
    console.log('GitHub Step Summary updated.');
} else {
    console.log('(Not in GitHub Actions – GITHUB_STEP_SUMMARY not set)');
}
